#!/bin/bash
echo "I will install Node environment"
apt autoremove -y
apt update -y
sudo apt install php7.4-cli
#sudo apt install -y php7.3-cli php7.3-fpm php7.3-opcache php7.3-curl php7.3-mbstring php7.3-pgsql php7.3-zip php7.3-xml php7.3-gd
sudo apt install -y php7.4-cli php7.4-fpm php7.4-opcache php7.4-curl php7.4-mbstring php7.4-pgsql php7.4-zip php7.4-xml php7.4-gd

#curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
#apt install nodejs
